name: Test

on:
  pull_request:


jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run terraform init
        run: terraform init
      - name: Select dev workspace
        run: terraform workspace select dev
      - name: Run terraform plan for dev
        run: terraform plan
      - name: Select prod workspace
        run: terraform workspace select prod
      - name: Run terraform plan for prod
        run: |
          terraform taint aws_dynamodb_table.test
          terraform plan

  after-plan:
    runs-on: ubuntu-latest
    needs:
      - plan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notify terraform plan result as PR comment for dev
        uses: ./
        id: plan-dev
        with:
          plan-job: plan
          plan-step: Run terraform plan for dev
          workspace: dev
      - name: Assertion
        run: |
          set -x
          diff <(jq --sort-keys . .github/workflows/dev/outside.json) <(jq --sort-keys . <<< '${{ steps.plan-dev.outputs.outside }}')
          diff <(jq --sort-keys . .github/workflows/dev/action.json)  <(jq --sort-keys . <<< '${{ steps.plan-dev.outputs.action }}')
          diff <(jq --sort-keys . .github/workflows/dev/output.json)  <(jq --sort-keys . <<< '${{ steps.plan-dev.outputs.output }}')
          diff <(jq --sort-keys . .github/workflows/dev/warning.json) <(jq --sort-keys . <<< '${{ steps.plan-dev.outputs.warning }}')
          diff <(jq --sort-keys . .github/workflows/dev/summary.json) <(jq --sort-keys . <<< '${{ steps.plan-dev.outputs.summary }}')
          [ '${{ steps.plan-dev.outputs.should-apply }}' = 'false' ]
      - name: Notify terraform plan result as PR comment for prod
        uses: ./
        id: plan-prod
        with:
          plan-job: plan
          plan-step: Run terraform plan for prod
          workspace: prod
      - name: Assertion
        run: |
          set -x
          diff <(jq --sort-keys . .github/workflows/prod/outside.json) <(jq --sort-keys . <<< '${{ steps.plan-prod.outputs.outside }}')
          diff <(jq --sort-keys . .github/workflows/prod/action.json)  <(jq --sort-keys . <<< '${{ steps.plan-prod.outputs.action }}')
          diff <(jq --sort-keys . .github/workflows/prod/output.json)  <(jq --sort-keys . <<< '${{ steps.plan-prod.outputs.output }}')
          diff <(jq --sort-keys . .github/workflows/prod/warning.json) <(jq --sort-keys . <<< '${{ steps.plan-prod.outputs.warning }}')
          diff <(jq --sort-keys . .github/workflows/prod/summary.json) <(jq --sort-keys . <<< '${{ steps.plan-prod.outputs.summary }}')
          [ '${{ steps.plan-prod.outputs.should-apply }}' = 'true' ]
