name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run terraform init
        run: terraform init
      - name: Run terraform plan
        run: terraform plan -out tfplan
      - name: Upload plan file
        uses: actions/upload-artifact@v3
        with:
          name: Terraform plan file
          path: tfplan
  
  after-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - plan
    steps:
      - name: Notify terraform plan result as PR comment
        uses: kota65535/github-terraform-plan-comment-action@lint-format
        id: plan-result
        with:
          plan-job-name: plan
          plan-step-name: Run terraform plan
